# theme: jekyll-theme-cayman
# remote_theme: pages-themes/dinky@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-dinky
title: ['Haozhe Liu']
description: ['AI Initiative, KAUST | Jarvis Lab, Tencent']
show_downloads: false
github:
  zip_url: http://example.com/download.zip
  another_url: another value
